version: '3.8'
services:
  mysql_db_docker_compose:
    image: mysql:8.0-oracle
    container_name: mysql_db_docker_compose
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - springboot-network
  qod:
    #image: qod:v3
    build: .
    container_name: qod
    networks:
      - springboot-network
    depends_on:
      - mysql_db_docker_compose
    ports:
      - "8080:8080"
networks:
  springboot-network:
    driver: bridge
